import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Card, Header, SectionSearch } from 'components';
import { api } from 'service/api';

import * as S from './styles';

export interface IUserData {
  avatar_url?: string;
  blog?: string;
  company?: string;
  followers?: string;
  following?: string;
  formattedDate?: string;
  public_repos?: string;
  twitter_username?: string;
  user_name?: string;
  name?: string;
  login?: string;
  bio?: string;
  location?: string;
  created_at?: string;
}

const Home: NextPage = () => {
  const [user, setUser] = useState<string>('octocat');
  const [userData, setUserData] = useState<IUserData>({});
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchFirstUser = async () => {
      try {
        const { data } = await api.get<IUserData>(`users/${user}`);

        const createdAt = data.created_at!;

        const formattedData = {
          ...data,
          formattedDate: new Date(createdAt)
            .toLocaleDateString('en-GB', {
              day: 'numeric',
              year: 'numeric',
              month: 'short',
            })
            .replace(',', ''),
        };
        setError('');
        setUserData(formattedData);
      } catch (error) {
        setError('Not results');
      }
    };

    fetchFirstUser();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleClick = async () => {
    try {
      setError('');
      const { data } = await api.get(`users/${user}`);

      const formattedData = {
        ...data,
        formattedDate: new Date(data.created_at)
          .toLocaleDateString('en-GB', {
            day: 'numeric',
            month: 'short',
            year: 'numeric',
          })
          .replace(',', ''),
      };

      setUserData(formattedData);
    } catch (error) {
      setError('Not results');
    }
  };

  return (
    <div>
      <Head>
        <title>devFinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="shortcut icon" href="favicon-32x32.png" />
        <link rel="apple-touch-icon" href="favicon-32x32.png" />
      </Head>
      <S.Container>
        <S.Main>
          <Header />
          <SectionSearch
            user={user}
            error={error}
            setUser={setUser}
            handleClick={handleClick}
          />
          <Card userData={userData} />
        </S.Main>
      </S.Container>
    </div>
  );
};

export default Home;
